# Waypoint patrol config
patrol:
  loop: true
  wait_duration: 2.0
  clear_costmaps_each_goal: true
  clear_costmaps_delay: 0.3
  clear_costmaps_service: /move_base/clear_costmaps

waypoints:
  - name: "起点"
    x: 0.0
    y: 0.0
    yaw: 0.0

  - name: "目标点A"
    x: 1.1270828247070312
    y: -0.717861533164978
    yaw: -1.57

  - name: "目标点B"
    x: 1.9868547916412354
    y: -0.02141129970550537
    yaw: 0.0
